defaults: &defaults

development:
  <<: *defaults

  # Secret tokens. Generate them with `rake secret`
  secret_key: "WndZNvO89uCk7nxj"
  devise_secret_key: "WndZNvO89uCk7nxj0"
  smtp_host: "smtp.mandrillapp.com"
  smtp_port: 587
  smtp_user: "app32689271@heroku.com"
  smtp_password: "TYuxdvFhNFGKyP7tleF8vg"
  host: 'thapymar.com.br'
  port: '3000'
  application_id: '6551a588a3e6842386539720e80c13e2cfc63bb69ab897f1f37aa88de20c1085'
  theme: 'unicoop'
  title: 'Thapymar'


test:
  <<: *defaults

  # Secret tokens. Generate them with `rake secret`
  secret_key: "WndZNvO89uCk7nxj"
  devise_secret_key: "WndZNvO89uCk7nxj0"
  smtp_host: "smtp.mandrillapp.com"
  smtp_port: 587
  smtp_user: "app32689271@heroku.com"
  smtp_password: "TYuxdvFhNFGKyP7tleF8vg"
  host: 'unicooprj.com.br'
  port: '3000'
  application_id: '6551a588a3e6842386539720e80c13e2cfc63bb69ab897f1f37aa88de20c1085'
  theme: 'unicoop'
  title: 'Unicoop'

production:
  <<: *defaults

  # Secret tokens. Generate them with `rake secret`
  secret_key: "WndZNvO89uCk7nxj"
  devise_secret_key: "WndZNvO89uCk7nxj0"
  smtp_host: "smtp.mandrillapp.com"
  smtp_port: 587
  smtp_user: "app32689271@heroku.com"
  smtp_password: "TYuxdvFhNFGKyP7tleF8vg"
  host: 'unicooprj.com.br'
  port: '80'
  application_id: '6551a588a3e6842386539720e80c13e2cfc63bb69ab897f1f37aa88de20c1085'
  theme: 'unicoop'
  title: 'Unicoop'
