defaults: &defaults

development:
  <<: *defaults

  # Secret tokens. Generate them with `rake secret`
  secret_key: "WndZNvO89uCk7nxj"
  devise_secret_key: "WndZNvO89uCk7nxj0"
  smtp_host: "smtp.mandrillapp.com"
  smtp_port: 587
  smtp_user: "vyctorbh@gmail.com"
  smtp_password: "rNd3LORstG56_Zey3fDOGw"  
  host: 'kurumin.xyz'
  port: '3001'
  application_id: '6551a588a3e6842386539720e80c13e2cfc63bb69ab897f1f37aa88de20c1085'
  theme: 'unicoop'
  title: 'Unicoop'


test:
  <<: *defaults

  # Secret tokens. Generate them with `rake secret`
  secret_key: "WndZNvO89uCk7nxj"
  devise_secret_key: "WndZNvO89uCk7nxj0"
  smtp_host: "smtp.mandrillapp.com"
  smtp_port: 587
  smtp_user: "vyctorbh@gmail.com"
  smtp_password: "rNd3LORstG56_Zey3fDOGw" 
  host: 'kurumin.xyz'
  port: '3001'
  application_id: '6551a588a3e6842386539720e80c13e2cfc63bb69ab897f1f37aa88de20c1085'
  theme: 'unicoop'
  title: 'Unicoop'
  
production:
  <<: *defaults

  # Secret tokens. Generate them with `rake secret`
  secret_key: "WndZNvO89uCk7nxj"
  devise_secret_key: "WndZNvO89uCk7nxj0"
  smtp_host: "smtp.mandrillapp.com"
  smtp_port: 587
  smtp_user: "vyctorbh@gmail.com"
  smtp_password: "rNd3LORstG56_Zey3fDOGw"
  host: 'kurumin.xyz'
  port: '3001'
  application_id: '6551a588a3e6842386539720e80c13e2cfc63bb69ab897f1f37aa88de20c1085'
  theme: 'unicoop'
  title: 'Unicoop'
