development:
  host: 191.101.2.6
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: unicoop_dev
  pool: 5
  username: postgres
  password: 123456

test:
  host: 191.101.2.6
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: unicoop_dev
  pool: 5
  username: postgres
  password: 123456

production:
  host: 191.101.2.6
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: unicoop_dev
  pool: 5
  username: postgres
  password: 123456

