development:
  host: 172.17.42.1
  port: 49157
  adapter: postgresql
  encoding: unicode
  database: db
  pool: 5
  username: root
  password: uxrBBRPNwFGh1ZgJ

test:
  host: 172.17.42.1
  port: 49157
  adapter: postgresql
  encoding: unicode
  database: db
  pool: 5
  username: root
  password: uxrBBRPNwFGh1ZgJ

production:
  host: 172.17.42.1
  port: 49157
  adapter: postgresql
  encoding: unicode
  database: db
  pool: 5
  username: root
  password: uxrBBRPNwFGh1ZgJ

