development:
  host: 45.55.243.147
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: geckodev
  pool: 5
  username: postgres
  password: Idon522#

test:
  host: 172.17.42.1
  port: 49158
  adapter: postgresql
  encoding: unicode
  database: db
  pool: 5
  username: root
  password: pNbYvk95Heu6ptDD

production:
  host: gogo.cbvsnzacabmc.us-east-1.rds.amazonaws.com
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: gogopark
  pool: 5
  username: gogopark
  password: Idon522#

